#!/bin/sh
# THIS FILE IS AUTOMATICALLY DISTRIBUTED BY PUPPET.  ANY CHANGES WILL BE
# OVERWRITTEN.

NICE=$(command -v nice)
IONICE=$(command -v ionice)

OUTPUT=$("${NICE}" -n 19 "${IONICE}" -c3 /usr/sbin/logrotate /etc/logrotate.d/hourly 2>&1)
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
    echo "${OUTPUT}"
fi
exit $EXITVALUE
